### PR TITLE
Adding Copal CHS-04TB DIP switch

### PR DESCRIPTION
**Pull request by cepr**

### CODE REVIEW

**Comment by jkriege2** [comment]
Hi1

as I'm currently updating this lib, using a script, I took the liberty to also add the full series of Copal CHS switches (+ several other types). See: https://github.com/KiCad/Buttons_Switches_THT.pretty/pull/14

OK for you?

Best,
JAN

**Comment by jkriege2** [comment]
OK; I pushed to this Repo now: https://github.com/KiCad/Buttons_Switches_SMD.pretty/pull/12
best,
JAN

**Comment by cepr** [comment]
Perfect, I will update my projects to use your version.
Thank you!

**Comment by cepr** [comment]
Closing as duplicate

**Pull request closed without merging**
