### PR TITLE
Add missing F.Paste to SMD DIP switch pads

### PR DESCRIPTION
**Pull request by ghost**
Fixing bug reported here: https://github.com/KiCad/Buttons_Switches_SMD.pretty/issues/24

### CODE REVIEW

**Comment by ghost** [comment]
The Travis errors were pre-existing.  I will update the PR to fix them.

**Comment by jkriege2** [comment]
Hi!

just a short sidenote ... I created these with a script: https://github.com/pointhi/kicad-footprint-generator/blob/master/scripts/DIP_packages/make_DIP_footprints.py

PS: I will review this PR, when you're done (I pressume, when Travis says OK?).

JAN

**Comment by ghost** [comment]
Thanks, Jan. It's ready for review. See what you think about size and position of Fab REF designator - it clashes with graphic of switch slides.

I can submit a separate PR to update the script if you like?

**Comment by jkriege2** [comment]
Hi!

what do you think about moving the REFDES like this:
2017-09-03 13_13_24-footprint editor no active library
2017-09-03 13_12_53-footprint editor no active library

I think a PR for the scripts would be great!

JAN

**Comment by ghost** [comment]
Looks good! I'll update this PR and open one for the script.

**Comment by ghost** [comment]
The script that needs most of the work is this tool script, called by `make_DIP_footprints.py`.

https://github.com/pointhi/kicad-footprint-generator/blob/master/scripts/tools/footprint_scripts_DIP.py

There is a bit of refactoring to do, since the handling of THT and SMD is closely coupled. I'll work on it this week.

For now, suggest not merging this PR.

**Comment by ghost** [comment]
First version of updated script working.  OK for 3 pole switches and larger ...

image

... but needs more work to set optimum position and size for 2 poles and smaller ...

image
 
Fixing the non-switch DIPs was easier :smile: 

image

**Comment by ghost** [comment]
@jkriege2 Footprints are ready for review.  All generated with the updated script:  https://github.com/pointhi/kicad-footprint-generator/pull/51

_Apart from the intended changes (added paste layer, second ref designator, etc), the file diffs show tiny changes in some (not all) of the text and line coordinates.  The change is typically 0.06mm.  This also happened with the original version of the script before I made the changes.  Not sure how the models in master branch of this repo ended up with these differences from the script output._

Some examples of the layout (with pads hidden) ...

image

image

**Comment by jkriege2** [comment]
nice work!

Thanks,
JAN

**Pull request merged**
