### PR TITLE
Added JS102011SAQN

### PR DESCRIPTION
**Pull request by SchrodingersGat**
This PR adds the JS102011SAQN SMT SPDT switch

http://www.digikey.com/product-detail/en/c-k/JS102011SAQN/401-1999-1-ND/1640114

fp
3d

### CODE REVIEW

**Comment by jkriege2** [comment]
Hi1

nice work. Two smaller changes please:
1. remove `${KISYS3DMOD}` from 3D model path
2. our check-scripts report an error on anchor placement (should be in the center of center pin)

best,
JAN

**Comment by SchrodingersGat** [comment]
1. I have updated the check for 10.8 here - https://github.com/KiCad/kicad-library-utils/pull/83 I do not think we should require KISYS3DMOD to be removed as this is generated by the Kicad software
1. The datasheet indicates that the pick-and-place origin is in the center of the switch body. We should change the anchor placement rule as "center of the pins" is not always correct - certainly not in this case.

**Comment by jkriege2** [comment]
ad 1) On my windows installation I get an error message whenever I open the 3D viewer in the footprint editor when that variable is present in the path, but the part does not exist (KISYS3DMOD is set correctly)... When ${KISYS3DMOD} is not there, I don't get that message ...

**Comment by SchrodingersGat** [comment]
What does that error message say?

**Comment by jkriege2** [comment]
2017-02-17 07_44_57-3d viewer

I also get it in the PCB editor, but the message appears only once per session (it seems). When I load another footprint that also does not have a 3D and matches the conditions above, the message does not appear a second time ...

So in sum I think this looks like a bug, as I would say there should not be a modal error message ... maybe a log-output somehwere, but blocking the GUI seems a bit harsh "just" because a 3D model was not found (IMHO).

What do you think?
JAN

**Comment by SchrodingersGat** [comment]
Yes I think this is a bug that should be reported.

A better idea would be to display a tick or cross icon next to each model path, showing if the model was found (or not).

For this time, I would not reject the model just because it has {KISYS3DMOD} - especially given this is what is created by KiCad itself.

**Comment by jkriege2** [comment]
About the anchor position: I already tried to have potentiometers where the anchor is at the center of the pot-axis, but without success ... So to me it seemed that the centered-between-pins rule was seen as very strickt (personally I wouldn't see it that way), but maybe we should discuss that a bit broader?

JAN

**Comment by SchrodingersGat** [comment]
I definitely think there are cases where the origin should not be the geometric centre between pads. The purpose of setting the origin is to help with component placement (via machine) and for non-symmetric footprints this needs to be adjusted appropriately. 

Do you have open PRs where the footprint origin is an putsran issue?

**Comment by jkriege2** [comment]
Hhmmm ... for switches, where you e.g. want to drill a hole in a housing front, I would also say the anchor should be in the center (same for potmeter axes), but for this SMD switch I would say we stick to KLC?

Best,
JAN

**Comment by jkriege2** [comment]
@SchrodingersGat What should we do on this?

**Comment by SchrodingersGat** [comment]
I think we should use the middle of the part (ignore KLC on this check) - look at page I-59 of the [datasheet](http://www.ckswitches.com/media/1422/js.pdf) where the switch is located in the tape. The centroid is on the middle of the package, not the pins.

**Comment by jkriege2** [comment]
OK!

should we maybe name such an exception in the KLC? I can think of a few component where this might make sense:
1. switches
2. buttons where you want the center to be at a specific location to match a frontpanel
3. LEDs (as above)
4. photosensors, light-barriers, ...
5. Pot-Meters

What do you think?
JAN

**Pull request merged**
