### PR TITLE
Add SW_SPST_KMR2_G (KMR2 with ground pin)

### PR DESCRIPTION
**Pull request by crteensy**
This is basically the button as the KMR2, but with an extra ground pin. Other pads are not as in the original KMR2 footprint since the original footprint has them rotated by 90 degrees (see https://github.com/KiCad/Buttons_Switches_SMD.pretty/issues/29)

### CODE REVIEW

**Comment by crteensy** [comment]
failed check: anchor not in center. This is expected since the footprint is asymmetric with respect to the x axis (in library). Datasheet shows anchor at center of main body (in this drawing the asymmetry is with respect to the drawing's x axis):
image

**Comment by jkriege2** [comment]
nice spot and nice fix. An exception from the center-KLC-rule is OK in this case. 

there's only one minor thing to fix, please add the 3D link to `${KISYS3DMOD}/Buttons_Switches_SMD.3dshapes/SW_SPST_KMR2.wrl` also to `SW_SPST_KMR2_G.kicad_mod`

In addition please rename `SW_SPST_KMR2_G` to  `SW_SPST_KMR2_GNDPad`

Thanks,
JAN

**Comment by crteensy** [comment]
I added the requested changes to the PR. However, the 3d model doesn't exist (in my installation?) and using it for the KMR2 button with ground pin would be slightly wrong.

**Comment by jkriege2** [comment]
Thanks,
JAN

**Pull request merged**
