### PR TITLE
Sw copal cs 4 13 nx

### PR DESCRIPTION
**Pull request by SchrodingersGat**
This PR adds two Copal switches:

* CS-4-12xx
* CS-4-13Nx

### CODE REVIEW

**Comment by jkriege2** [comment]
Hi!

also nice work! Please fix the 3D model links (remove `${KISYS3DMOD}` and check names) ... out check-scripts report errors!

cu
JAN

**Comment by SchrodingersGat** [comment]
Kicad prepends  {$KISYS3DMOD} to the 3D filename. I think we should adjust our script to ignore this prefix (if it is there).

Note: The 3D model loads fine if {$KISYS3DMOD} is there or not.

I have fixed the naming of these models but left the prefix in. There is an update to 10.8 here - https://github.com/KiCad/kicad-library-utils/pull/83

**Comment by SchrodingersGat** [comment]
@jkriege2 Travis tells me all is ok ;) Wanna check?

**Comment by jkriege2** [comment]
nice work.

Please fix the pad numberig for this switch, so it matches with the symbol in switches.lib ... or post a special symbol (pad4 is common in four footprint, but pin3 is common in the symbol):
2017-04-06 21_47_41-choose component 45 items loaded


Thanks,
JAN

**Comment by evanshultz** [comment]
@SchrodingersGat Will you be able to wrap up this PR soon?

**Comment by SchrodingersGat** [comment]
Perhaps we should be reconsidering the numbering for the switch symbols?

Common practice seems to be to label the common pin 'C'. This means that it is consistent across e.g. SPDT SP3T.

Any other numbering we pick is going to mismatch the datasheet.

**Reference**
* https://media.digikey.com/pdf/Data%20Sheets/C&K/RTE_Series_Dip_Rev_Feb_2011_Ds.pdf
* https://www.nidec-copal-electronics.com/e/catalog/switch/cs-4.pdf

What do you think? THere are not many switch footprints so we could methodically make the change.

**Comment by evanshultz** [comment]
Hmmm... It's a bit annoying but seems the best method to me with the separation between symbol and footprint that KiCad gives (which I like). @SchrodingersGat Are you up for taking care of that task?

Anybody else want to weight in? @jkriege2 @poeschlr

**Comment by SchrodingersGat** [comment]
If we get consensus on this I will bear responsibility for updating the footprints and symbols. Yay fun.

**Comment by jkriege2** [comment]
Hi!

hmmm ... generally I'm OK with this, although we usually only use numbers ... so people somehow need to be informed about this ... KLC?

Why not then make the "special" common pin simply pin1?

Best,
JAN

PS: I will be quiet for a few days/weeks, as we're relocating and I won't have internet back for  that duration.

**Comment by poeschlr** [comment]
> generally I'm OK with this, although we usually only use numbers

I would say if both the symbol and footprint are specialized for one component and the datasheet does not use numbers, then letters are ok. (If the datasheet does use this nomenclature on the footprint description.)
An example where this is already used is the relay library.

**Comment by evanshultz** [comment]
@jkriege2 
If the switch is DPDT, there will be two common pins. Perhaps C1 and C2? That would be one reason to use this pin naming system for the footprints so different switch symbols still map correctly to footprints.

**Comment by jkriege2** [comment]
If the symbol+footprint are specialized: no problem, but I understood we are talking about changing the general symbols? If so that should go into KLC + maybe a check that gives an error if there is no COMMON-pin in a symbol in switches with at least 3 pins ...

What do you think?
JAN

**Comment by SchrodingersGat** [comment]
I have raised a [more general discussion point](https://github.com/KiCad/kicad-library/issues/1355) on this issue. It pertains to far more than just switches, I feel...

**Comment by evanshultz** [comment]
@jkriege2 Jan, you started reviewing this PR. Would you be able to finish it?

**Comment by SchrodingersGat** [comment]
@evanshultz this is mostly in my court at the moment, I need to make further changes to this.

**Comment by Shackmeister** [comment]
@SchrodingersGat are you planning on finishing this? :)

**Comment by jkriege2** [comment]
@SchrodingersGat will you go on on this?

Bast,
JAN

**Comment by SchrodingersGat** [comment]
Sorry, no time at the moment. Some thought does need to go into how the generic switch symbols are drawn... But not by me currently.

**Pull request closed without merging**
