### PR TITLE
Add footprints for Panasonic EVQPUx

### PR DESCRIPTION
**Pull request by dingari**
I've created footprints for all variants of the Panasonic EVQPUx buttons.

Datasheet: http://industrial.panasonic.com/cdbs/www-data/pdf/ATV0000/ATV0000CE5.pdf

I've run the `check_kicad_mod` script on the footprints and it says I'm violating rule 8.2, saying the anchor is not in the center. But the anchor is centered according to the datasheet.

### CODE REVIEW

**Comment by SchrodingersGat** [comment]
Hi @dingari generally these are pretty good - I have a few points (refer to image below)

1. Rotate footprint so pin-1 is on the left
1. Move second RefDes `%R` to location (0,0)
1. Shorten footprint name to start with `Panasonic_...`

image

Also, the K/B variant has a very long line on the Courtyard layer, that extends a long way to the left of the footprint - please fix this.

**Comment by dingari** [comment]
Hi, I've fixed those things. Should be able to merge now.

**Comment by SchrodingersGat** [comment]
Great work and thank you for your contribution

**Comment by SchrodingersGat** [comment]
@dingari actually I think that you have commonized the wrong pads here.

image

The TOP pads are connected together as are the BOTTOM pads. Your PR has the LEFT common and the RIGHT common.

I merged this too quickly - can you issue a new PR fixing these issues?

**Comment by dingari** [comment]
Oh, you're totally right. I'll fix it in a new PR.

Thanks for spotting that, I'm about to get a board fabricated using these footprints. Would've been a bummer!

**Comment by SchrodingersGat** [comment]
Glad to have helped! These switches can always be confusing. Please tag me when you submit the new PR

**Pull request merged**
