### PR TITLE
Add footprints for Panasonic EVQPL push-button

### PR DESCRIPTION
**Pull request by dingari**
Introducing 3d modules for Panasonic EVQPL type pushbutton (both with push-plate and without).

I've submitted a pull request in the kicad-library repository with 3D models for these footprints.

http://industrial.panasonic.com/cdbs/www-data/pdf/ATK0000/ATK0000CE3.pdf

### CODE REVIEW

**Comment by poeschlr** [comment]
screenshot from 2017-02-25 17-17-27

Looks ok. (very similar to all other button footprints.)
@SchrodingersGat:
Only question is do we really want the circle on the fab layer?
(Yes this is not really defined in the KLC.)

should the manufacturer name be included in the footprint naming?

**Comment by dingari** [comment]
Hi, I don't really mind the circle in the fab layer. Do you want it removed?

The manufacturer should ideally be included in the name, but there are other footprints already in the repository (EVP, EVQ series) and I tried to keep the name consistent with those.

**Comment by SchrodingersGat** [comment]
I would vote to *keep* the circle on F.Fab. It speaks to the function of the part and is still very simplistic.

**Comment by dingari** [comment]
What about the footprint naming? Should we keep it as is or rename it to include the manufacturer? If we do that, I´d suggest editing the other footprints from Panasonic as well.

**Comment by jkriege2** [comment]
I would add the manufacturer, although that's not (yet) common in this lib ...

Best,
JAN

PS: Please also correct the courtyard offset. It should be 0.5mm  measured from the outside of the pads (or the F.Fab, but the latter is inside the pads):
2017-03-08 21_08_24-footprint editor no active library

**Comment by dingari** [comment]
I've renamed the footprints. Regarding the courtyard offset, the KLC states 

>Courtyard clearance is 0.25mm except for components smaller than 0603 at 0.15mm, connectors, SMD canned capacitors and crystals at 0.5mm and BGA at 1.0mm. (IPC-7251, IPC-7351B)

Are there exceptions to this for buttons? I'll be happy to change it, but I thought I was following the KLC.

**Comment by dingari** [comment]
I've increased the courtyard clearance to 0.5mm, however the `check_kicad_mod.py` script seems to disagree. The pad edge extremes are `x = 2.75` and `y = 2.7`, which should make the 0.5mm offset `x = 3.25` and `y = 3.2`.

But the script (for some reason) wants `{'y': -3.2, 'x': -3.33, 'height': 6.4, 'width': 6.65}mm.` Why is this?

**Comment by jkriege2** [comment]
Hi!

sorry, but those scripts are currently buggy (new versions are underway ;-) ... I will check manually on the weekend, but from what you say it should be OK!

Best,
JAN

**Comment by dingari** [comment]
Hi, where do we stand on this PR?

**Comment by jkriege2** [comment]
Looks good (sorry for the delay ... I've been on holidays ;-)

One final change please: Set the pin number of the pads on the side to 0. The DS states that these should be GND ... and without that you cannot connect these to ANY pin. (We might also have to add a symbol of a push-button with shielding then ;-)

Also the silkscreen-lines end very close to the side-pads (0s) ... please move then a bit (0.1-0.2mm???) up/down to ensure a bit of clearance.

Best,
JAN

**Comment by dingari** [comment]
No problem, I've fixed those issues you mentioned :)

One more thing, shouldn't I rename these to start with "Panasonic..." to be consistent with other footprints in this family?

**Comment by jkriege2** [comment]
nice work!

Thanks,
JAN

**Pull request merged**
