### PR TITLE
add Coto SPST Reed Switches

### PR DESCRIPTION
**Pull request by Telemin**
Tried to comply with the KLC as best I could understand.  Please advise me if there are issues.

See http://cotorelay.com/sensors-switches/ for details of the parts

### CODE REVIEW

**Comment by pointhi** [comment]
Hy,

please fix courtyard line:

```
6.7. Courtyard clearance is 0.25mm except for components smaller than 0603 at 0.15mm, connectors, SMD canned capacitors and crystals at 0.5mm and BGA at 1.0mm. (IPC-7251, IPC-7351B)
```

**Comment by Telemin** [comment]
Okay I can do that. Just to clarify: Should the courtyard clearance be _exactly_ those distances, or _at least_ those distances?

**Comment by pointhi** [comment]
You have to align the courtjard on a 0.05mm grid, and normally the clearances have only slight varations from the 0.25mm to match the grid. But you don't have to follow the exact outline of the component. A simple rect is currently enought.

**Comment by Telemin** [comment]
Okay.  Hopefully that should do it.

**Comment by pointhi** [comment]
### SW_SPST_REED_CT10-XXXX-G4
- `REF**` should be moved outsite the component (to be readable after assembly)

---
- It's not required, but keywords could also be useful (please note, keywords are sperated by spaces)

the rest looks fine to me

**Comment by Telemin** [comment]
Fixed. Keywords added.  Thank you for your patience.

**Comment by pointhi** [comment]
thanks for you contribution

**Pull request merged**
