### PR TITLE
Add ALPS SKQG button, slight revisions to other footprints

### PR DESCRIPTION
**Pull request by Ratfink**
- Added SW_SPST_SKQG footprint for ALPS SKQG series pushbutton switches
- KLC corrections to SW_SPST_FSMSM, SW_SPST_KMR2, and SW_SPST_PTS645

### CODE REVIEW

**Comment by pointhi** [comment]
Hy,

please fix the little KLC issue (set the attribute to smd):

```
checking module: SW_SPST_PTS645
  Violating Rule 10.5
    Attributes is set to the appropriate value, see tooltip for more information.
checking module: SW_SPST_SKQG
  Violating Rule 10.5
    Attributes is set to the appropriate value, see tooltip for more information.
```

**Comment by Ratfink** [comment]
Thanks for pointing those out.  I've fixed the issues.

**Comment by pointhi** [comment]
Ok, I looked more detailed over the footprints and found this outstanding (KLC) issues:

### SW_SPST_SKQG.kicad_mod

```
6.5. Silkscreen is not superposed to pads, its outline is completely visible after board assembly, uses 0.15mm line width and provides a reference mark for pin 1. (IPC-7351)
```

### SW_SPST_PTS645.kicad_mod
- text fields should be moved out so they are easy readable by default

### SW_SPST_KMR2.kicad_mod

http://datasheet.octopart.com/KMR211GLFS-ITT-datasheet-13389051.pdf

```
6.5. Silkscreen is not superposed to pads, its outline is completely visible after board assembly, uses 0.15mm line width and provides a reference mark for pin 1. (IPC-7351)
```
- You should move the component outline into the correct layer (`F.Fab` or `Dwgs.User`). Furthermore, the outline would then be continius, and not so chunked as yet

I know some of this issues are not created by you, but it would be greate to fix those too before merging.

**Comment by Ratfink** [comment]
Alright, I've fixed those issues as well.

**Comment by pointhi** [comment]
please fix KLC issue (issue created in f7b592f):

```
checking module: SW_SPST_SKQG
  Violating Rule 10.4
    Value is filled with footprint name and is placed on the fabrication layer.
```

value has to be the same as the name of the footprint, and reference has always to be `REF**`

**Comment by Ratfink** [comment]
Okay, that's fixed now too.  Sorry about all these problems, I know I must look like a fool by now.

**Comment by pointhi** [comment]
thanks for your contribution

**Pull request merged**
